#!/bin/bash
echo "Enter the name:"
read name
touch $name
printf "#include <stdio.h>\n/**\n * main - Entry point\n *\n * Return: Always 0 (Success)\n */\nint main(void)\n{\n	return (0);\n}" > $name
vi $name
